version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk maven
      - run:
          name: Build Spring Boot JAR
          working_directory: ./backend
          command: mvn clean package
      - run:
          name: Verify Build Artifacts
          command: ls -al ./backend/target
      - persist_to_workspace:
          root: ./backend
          paths:
            - target

  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - attach_workspace:
          at: /home/circleci/project/backend
      - run:
          name: Verify Workspace Contents
          command: ls -al /home/circleci/project/backend/target
      - run:
          name: Deploy to Remote Server
          command: |
            scp /home/circleci/project/backend/target/DoBuy-0.0.1-SNAPSHOT.jar handsomets9@104.199.189.44:/home/handsomets9/DoBuy-0.0.1-SNAPSHOT.jar
            ssh handsomets9@104.199.189.44 "
              pkill -f 'DoBuy-0.0.1-SNAPSHOT.jar' || true
              nohup java -jar /home/handsomets9/DoBuy-0.0.1-SNAPSHOT.jar > /home/handsomets9/app/app.log 2>&1 &
            "

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
