# Mysql
# demo DB name
#spring.datasource.url=jdbc:mysql://localhost:3306/dobuy?userSSL=false&serverTimezone=UTC
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=1qaz@WSX


# Hibernate
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MYSQL

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties.hibernate.dialect.storage_engine: innodb
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy=org:
#          hibernate:
#            boot:
#              model:
#                naming: PhysicalNamingStrategyStandardImpl
#    generate-ddl: true
#    show-sql: true
#    open-in-view: false
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password:  # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


#logging:
#  level:
#    org.hibernate:
#      SQL: DEBUG
#      type: TRACE